version: "2"

linters:
  # condider to add: cyclop
  default: none
  enable:
    - bodyclose
    - containedctx
    - dupl
    - err113
    - errcheck
    - exhaustive
    - fatcontext
    - forcetypeassert
    
  exclusions:
    rules:
      - path: _test\.go
        linters:
        - err113
        - errcheck